export const BOOK_DETAILS = {
  id: "1",
  title: "A Culpa é das Estrelas",
  description:
    "Hazel foi diagnosticada com câncer aos treze anos e agora, aos dezesseis, sobrevive graças a uma droga revolucionária que detém a metástase em seus pulmões. Ela sabe que sua doença é terminal e passa os dias vendo tevê e lendo Uma aflição imperial, livro cujo autor deixou muitas perguntas sem resposta. ",
  authors: ["Jonh Green"],
  pageCount: 288,
  category: "Romance",
  imageUrl: "https://files-books.ioasys.com.br/Book-0.jpg",
  isbn10: "0062856626",
  isbn13: "978-0062856623",
  language: "Inglês",
  publisher: "Intrínseca",
  published: 2002,
};

export const BOOK_CARD_DATA = {
  data: [
    {
      id: "1",
      title: "A Culpa é das Estrelas",
      description:
        "Hazel foi diagnosticada com câncer aos treze anos e agora, aos dezesseis, sobrevive graças a uma droga revolucionária que detém a metástase em seus pulmões. Ela sabe que sua doença é terminal e passa os dias vendo tevê e lendo Uma aflição imperial, livro cujo autor deixou muitas perguntas sem resposta. ",
      authors: ["Jonh Green"],
      pageCount: 288,
      category: "Romance",
      imageUrl: "https://files-books.ioasys.com.br/Book-0.jpg",
      isbn10: "0062856626",
      isbn13: "978-0062856623",
      language: "Inglês",
      publisher: "Intrínseca",
      published: 2002,
    },
    {
      id: "2",
      title: "A Culpa é das Estrelas",
      description:
        "Hazel foi diagnosticada com câncer aos treze anos e agora, aos dezesseis, sobrevive graças a uma droga revolucionária que detém a metástase em seus pulmões. Ela sabe que sua doença é terminal e passa os dias vendo tevê e lendo Uma aflição imperial, livro cujo autor deixou muitas perguntas sem resposta. ",
      authors: ["Jonh Green"],
      pageCount: 288,
      category: "Romance",
      imageUrl: "https://files-books.ioasys.com.br/Book-0.jpg",
      isbn10: "0062856626",
      isbn13: "978-0062856623",
      language: "Inglês",
      publisher: "Intrínseca",
      published: 2002,
    },
    {
      id: "3",
      title: "A Culpa é das Estrelas",
      description:
        "Hazel foi diagnosticada com câncer aos treze anos e agora, aos dezesseis, sobrevive graças a uma droga revolucionária que detém a metástase em seus pulmões. Ela sabe que sua doença é terminal e passa os dias vendo tevê e lendo Uma aflição imperial, livro cujo autor deixou muitas perguntas sem resposta. ",
      authors: ["Jonh Green"],
      pageCount: 288,
      category: "Romance",
      imageUrl: "https://files-books.ioasys.com.br/Book-0.jpg",
      isbn10: "0062856626",
      isbn13: "978-0062856623",
      language: "Inglês",
      publisher: "Intrínseca",
      published: 2002,
    },
    {
      id: "4",
      title: "A Culpa é das Estrelas",
      description:
        "Hazel foi diagnosticada com câncer aos treze anos e agora, aos dezesseis, sobrevive graças a uma droga revolucionária que detém a metástase em seus pulmões. Ela sabe que sua doença é terminal e passa os dias vendo tevê e lendo Uma aflição imperial, livro cujo autor deixou muitas perguntas sem resposta. ",
      authors: ["Jonh Green"],
      pageCount: 288,
      category: "Romance",
      imageUrl: "https://files-books.ioasys.com.br/Book-0.jpg",
      isbn10: "0062856626",
      isbn13: "978-0062856623",
      language: "Inglês",
      publisher: "Intrínseca",
      published: 2002,
    },
    {
      id: "5",
      title: "A Culpa é das Estrelas",
      description:
        "Hazel foi diagnosticada com câncer aos treze anos e agora, aos dezesseis, sobrevive graças a uma droga revolucionária que detém a metástase em seus pulmões. Ela sabe que sua doença é terminal e passa os dias vendo tevê e lendo Uma aflição imperial, livro cujo autor deixou muitas perguntas sem resposta. ",
      authors: ["Jonh Green"],
      pageCount: 288,
      category: "Romance",
      imageUrl: "https://files-books.ioasys.com.br/Book-0.jpg",
      isbn10: "0062856626",
      isbn13: "978-0062856623",
      language: "Inglês",
      publisher: "Intrínseca",
      published: 2002,
    },
    {
      id: "6",
      title: "A Culpa é das Estrelas",
      description:
        "Hazel foi diagnosticada com câncer aos treze anos e agora, aos dezesseis, sobrevive graças a uma droga revolucionária que detém a metástase em seus pulmões. Ela sabe que sua doença é terminal e passa os dias vendo tevê e lendo Uma aflição imperial, livro cujo autor deixou muitas perguntas sem resposta. ",
      authors: ["Jonh Green"],
      pageCount: 288,
      category: "Romance",
      imageUrl: "https://files-books.ioasys.com.br/Book-0.jpg",
      isbn10: "0062856626",
      isbn13: "978-0062856623",
      language: "Inglês",
      publisher: "Intrínseca",
      published: 2002,
    },
    {
      id: "7",
      title: "A Culpa é das Estrelas",
      description:
        "Hazel foi diagnosticada com câncer aos treze anos e agora, aos dezesseis, sobrevive graças a uma droga revolucionária que detém a metástase em seus pulmões. Ela sabe que sua doença é terminal e passa os dias vendo tevê e lendo Uma aflição imperial, livro cujo autor deixou muitas perguntas sem resposta. ",
      authors: ["Jonh Green"],
      pageCount: 288,
      category: "Romance",
      imageUrl: "https://files-books.ioasys.com.br/Book-0.jpg",
      isbn10: "0062856626",
      isbn13: "978-0062856623",
      language: "Inglês",
      publisher: "Intrínseca",
      published: 2002,
    },
    {
      id: "8",
      title: "A Culpa é das Estrelas",
      description:
        "Hazel foi diagnosticada com câncer aos treze anos e agora, aos dezesseis, sobrevive graças a uma droga revolucionária que detém a metástase em seus pulmões. Ela sabe que sua doença é terminal e passa os dias vendo tevê e lendo Uma aflição imperial, livro cujo autor deixou muitas perguntas sem resposta. ",
      authors: ["Jonh Green"],
      pageCount: 288,
      category: "Romance",
      imageUrl: "https://files-books.ioasys.com.br/Book-0.jpg",
      isbn10: "0062856626",
      isbn13: "978-0062856623",
      language: "Inglês",
      publisher: "Intrínseca",
      published: 2002,
    },
    {
      id: "9",
      title: "A Culpa é das Estrelas",
      description:
        "Hazel foi diagnosticada com câncer aos treze anos e agora, aos dezesseis, sobrevive graças a uma droga revolucionária que detém a metástase em seus pulmões. Ela sabe que sua doença é terminal e passa os dias vendo tevê e lendo Uma aflição imperial, livro cujo autor deixou muitas perguntas sem resposta. ",
      authors: ["Jonh Green"],
      pageCount: 288,
      category: "Romance",
      imageUrl: "https://files-books.ioasys.com.br/Book-0.jpg",
      isbn10: "0062856626",
      isbn13: "978-0062856623",
      language: "Inglês",
      publisher: "Intrínseca",
      published: 2002,
    },
    {
      id: "10",
      title: "A Culpa é das Estrelas",
      description:
        "Hazel foi diagnosticada com câncer aos treze anos e agora, aos dezesseis, sobrevive graças a uma droga revolucionária que detém a metástase em seus pulmões. Ela sabe que sua doença é terminal e passa os dias vendo tevê e lendo Uma aflição imperial, livro cujo autor deixou muitas perguntas sem resposta. ",
      authors: ["Jonh Green"],
      pageCount: 288,
      category: "Romance",
      imageUrl: "https://files-books.ioasys.com.br/Book-0.jpg",
      isbn10: "0062856626",
      isbn13: "978-0062856623",
      language: "Inglês",
      publisher: "Intrínseca",
      published: 2002,
    },
    {
      id: "11",
      title: "A Culpa é das Estrelas",
      description:
        "Hazel foi diagnosticada com câncer aos treze anos e agora, aos dezesseis, sobrevive graças a uma droga revolucionária que detém a metástase em seus pulmões. Ela sabe que sua doença é terminal e passa os dias vendo tevê e lendo Uma aflição imperial, livro cujo autor deixou muitas perguntas sem resposta. ",
      authors: ["Jonh Green"],
      pageCount: 288,
      category: "Romance",
      imageUrl: "https://files-books.ioasys.com.br/Book-0.jpg",
      isbn10: "0062856626",
      isbn13: "978-0062856623",
      language: "Inglês",
      publisher: "Intrínseca",
      published: 2002,
    },
    {
      id: "12",
      title: "A Culpa é das Estrelas",
      description:
        "Hazel foi diagnosticada com câncer aos treze anos e agora, aos dezesseis, sobrevive graças a uma droga revolucionária que detém a metástase em seus pulmões. Ela sabe que sua doença é terminal e passa os dias vendo tevê e lendo Uma aflição imperial, livro cujo autor deixou muitas perguntas sem resposta. ",
      authors: ["Jonh Green"],
      pageCount: 288,
      category: "Romance",
      imageUrl: "https://files-books.ioasys.com.br/Book-0.jpg",
      isbn10: "0062856626",
      isbn13: "978-0062856623",
      language: "Inglês",
      publisher: "Intrínseca",
      published: 2002,
    },
    // {
    //   id: "13",
    //   title: "A Culpa é das Estrelas",
    //   description:
    //     "Hazel foi diagnosticada com câncer aos treze anos e agora, aos dezesseis, sobrevive graças a uma droga revolucionária que detém a metástase em seus pulmões. Ela sabe que sua doença é terminal e passa os dias vendo tevê e lendo Uma aflição imperial, livro cujo autor deixou muitas perguntas sem resposta. ",
    //   authors: ["Jonh Green"],
    //   pageCount: 288,
    //   category: "Romance",
    //   imageUrl: "https://files-books.ioasys.com.br/Book-0.jpg",
    //   isbn10: "0062856626",
    //   isbn13: "978-0062856623",
    //   language: "Inglês",
    //   publisher: "Intrínseca",
    //   published: 2002,
    // },
  ],
  page: 1,
  totalPages: 34,
  totalItems: 674,
};
